services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=
  wasm:
    build:
      context: .
      dockerfile: composeApp/Dockerfile
    ports:
      - "8081:80"